version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=node2
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - TELEGRAM_CHANNEL_ID=$TELEGRAM_CHANNEL_ID
  app2:
    build:
      context: ../../phoenix/node2
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - db
      - rabbit
      - app
    environment:
      - URL_HOST=localhost
      - URL_PORT=80
      - PORT=80
      - DATABASE_URL=postgres://postgres:postgres@db/node2?pool_size=15
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
